name: "publish github pages"

description: "Generate Epythet documentation and push to github pages branch"

inputs:
  project-name:
    description: "Name of python project"
    required: true

  docs-branch:
    description: "Branch to push documentation build"
    required: false
    default: "docs"

  python-version:
    description: "Python version used to generate documentation"
    required: false
    default: "3.10"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Create or checkout docs branch
      run: |
        git pull
        git checkout $(git rev-parse --verify --quiet "${{ inputs.docs-branch }}" || echo '-b "${{ inputs.docs-branch }}"')
      shell: bash

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip -q install semver axblack twine wads isee
        isee install-requires
      shell: bash

    - name: Format source code
      run: black  --line-length=88 .
      shell: bash

    - name: Update version number
      run: |
        export VERSION=$(isee gen-semver)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        isee update-setup-cfg
      shell: bash

    - name: Package
      run: |
        python setup.py sdist
        echo "PKG_PATH=dist/${{ inputs.project-name }}-$VERSION.tar.gz" >> $GITHUB_ENV
      shell: bash

    - name: Generate Documentation
      run: |
        pip install $PKG_PATH
        isee generate-documentation
      shell: bash

    - name: Publish
      run: |
        epythet make . github
      shell: bash

    - name: Push Changes to docs branch
      run: |
        git push --set-upstream origin docs_branch
        pack check-in "**CI** Formatted code + Updated version number and documentation. [skip ci]" --auto-choose-default-action --bypass-docstring-validation --bypass-tests --bypass-code-formatting --verbose
      shell: bash

    - name: Tag Repository
      run: isee tag-repo $VERSION
      shell: bash
